name: Push

on:
  push:
    branches:
      - master
      - '*-maintenance'
      - symbioze-osd # SYMBIOZE: build the fork branch
  workflow_dispatch: # SYMBIOZE: allow manual re-runs

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
